const RAFFLE_STATES = {
  NO_REQUEST: 0,
  REQUEST_PENDING: 1,
  INCONCLUSIVE: 2
};

const ZERO_BYTES32 = '0x0';

const DEFAULT_GRACE_PERIOD = '604800'; // 1 week in seconds

module.exports = {
  RAFFLE_STATES,
  DEFAULT_GRACE_PERIOD,
  ZERO_BYTES32
};
